# Generated by Django 3.0.6 on 2020-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('institute_code', models.CharField(default='0x313', max_length=20, unique=True)),
                ('password', models.CharField(max_length=257)),
            ],
        ),
    ]
