# Generated by Django 3.0.6 on 2020-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_code',
            field=models.CharField(default='7a0e52', max_length=20, unique=True),
        ),
    ]
