# Generated by Django 3.0.6 on 2020-05-27 10:45

from django.db import migrations, models
import mentor.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20200527_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_code',
            field=models.CharField(default=mentor.models.random_code, max_length=20, unique=True),
        ),
    ]
