# Generated by Django 3.0.6 on 2020-05-24 06:51

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevel1',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='categorylevel2',
            name='category_level_1',
            field=models.ForeignKey(default=0, on_delete=models.SET(question.models.create_default_category), to='question.CategoryLevel1'),
        ),
    ]
