# Generated by Django 3.0.6 on 2020-05-27 11:13

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=question.models.create_default_category2, on_delete=models.SET(question.models.create_default_category2), related_name='questions', to='question.CategoryLevel2'),
        ),
    ]
