# Generated by Django 3.0.6 on 2020-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/images/options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(null=True, upload_to='uploads/images/question/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_image',
            field=models.ImageField(null=True, upload_to='uploads/images/solution/'),
        ),
    ]
