# Generated by Django 3.0.6 on 2020-05-25 05:18

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200524_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevel2',
            name='category_level_1',
            field=models.ForeignKey(on_delete=models.SET(question.models.create_default_category1), related_name='sub_categories', to='question.CategoryLevel1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(question.models.create_default_category2), related_name='questions', to='question.CategoryLevel2'),
        ),
    ]
