# Generated by Django 3.0.6 on 2020-05-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not_attended', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_questions', models.IntegerField()),
                ('total_duration', models.TimeField()),
                ('negative_marking', models.BooleanField(default=False)),
                ('commence_at', models.DateTimeField()),
                ('stop_commenceing_after', models.DateTimeField()),
                ('show_score', models.BooleanField(default=False)),
                ('show_answers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_questions', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not_attended', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='student.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Options')),
                ('student_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='tests.StudentQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_attended_questions', to='tests.TestPartition'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='question.Question'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student.Student'),
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.TestPartition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='question.Question')),
            ],
            options={
                'unique_together': {('partition', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentquestion',
            unique_together={('partition', 'question', 'student')},
        ),
    ]
