# Generated by Django 3.0.6 on 2020-05-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('question', '0005_auto_20200525_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_questions', models.IntegerField()),
                ('total_duration', models.TimeField()),
                ('negative_marking', models.BooleanField(default=False)),
                ('commence_at', models.DateTimeField()),
                ('stop_commenceing_after', models.DateTimeField()),
                ('show_score', models.BooleanField(default=False)),
                ('show_answers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.Test')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TestPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_questions', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not_attended', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='student.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tests.Test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not_attended', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('duration', models.TimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tests.TestQuestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student.Student')),
            ],
        ),
    ]
