# Generated by Django 3.0.6 on 2020-05-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200525_0518'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Options')),
                ('student_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='tests.StudentQuestion')),
            ],
        ),
    ]
