# Generated by Django 3.0.6 on 2020-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200525_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestions',
            name='dum',
            field=models.CharField(blank=True, default='00', max_length=2, null=True),
        ),
    ]
