# Generated by Django 3.0.6 on 2020-05-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200525_0518'),
        ('tests', '0004_testquestions_dum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testquestions',
            unique_together={('partition', 'question')},
        ),
        migrations.RemoveField(
            model_name='testquestions',
            name='dum',
        ),
    ]
